# -*- coding: utf-8 -*-
"""Contextual Web-Based Q&A System Using Gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PqSv3RyS3bAUlPRCWeLjvJARGlQwds-k

# ***Connecting With Cuda First And Chech It Connected Or Not***
"""

! nvidia-smi

"""# ***Install All The Dependency***"""

!pip install streamlit pyngrok requests beautifulsoup4 faiss-cpu sentence-transformers transformers

"""# ***Use BeautifulSoup To Extract The Text***"""

import requests
from bs4 import BeautifulSoup

def extract_text_from_urls(urls):
    text_data = []
    for url in urls:
        response = requests.get(url)
        soup = BeautifulSoup(response.text, "html.parser")
        # Remove script/style
        for tag in soup(["script", "style"]):
            tag.decompose()
        # Extract visible text
        text = soup.get_text(separator=' ', strip=True)
        text_data.append(text)
    return text_data

"""# ***Extract WikiPidea Deep_Learning Article Using Beautiful Soup***"""

urls = ["https://en.wikipedia.org/wiki/Deep_learning"]

web_text = extract_text_from_urls(urls)

# Print first 1000 characters from the first webpage
print(web_text[0][:1000])

"""# ***Create The Embedding using sentence-transformers + Vector Search using FAISS***"""

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

"""# ***Load The ALL-MiniLM-L6-v2 Model Using Sentence Transformers We Can Use Hugging-Face-Hub Model Also***"""

# Load the model Using Sentence Transformers
embed_model = SentenceTransformer("all-MiniLM-L6-v2")

"""# ***Take The Example Text Chunk For Embedding Purpose***"""

text_chunks = [
    "Deep learning is a subset of machine learning that uses neural networks.",
    "Machine learning involves training models on data.",
    "Natural language processing helps machines understand human language.",
    "Neural networks are used in both deep learning and image recognition."
]

"""# ***Create The Embedding***"""

embeddings = embed_model.encode(text_chunks)

# Print embeddings (first one)
print("First Embedding Vector (chunk 1):")
print(embeddings[0])

# Check shape
print("\nShape of All Embeddings:", embeddings.shape)

"""# ***Seeing All The Embeddings***"""

for i, emb in enumerate(embeddings):
    print(f"\n🔹 Embedding {i+1} for chunk: {text_chunks[i]}")
    print(emb)

"""# ***Create The Chunk Data Function***"""

def split_into_chunks(text_list, chunk_size=200):
    chunks = []
    for text in text_list:
        words = text.split()
        for i in range(0, len(words), chunk_size):
            chunk = " ".join(words[i:i+chunk_size])
            chunks.append(chunk)
    return chunks

"""# ***Create FAISS index function***"""

def create_faiss_index(chunks):
    embeddings = embed_model.encode(chunks)
    index = faiss.IndexFlatL2(embeddings.shape[1])
    index.add(np.array(embeddings))
    return index, embeddings

"""# ***Create The Gemini Pro API Key With os Environment + Add Langmith Also For Tracing Purposes***"""

import os
from google.colab import userdata

! pip install google-generativeai

import google.generativeai as genai
genai.configure(api_key="AIzaSyDGqVBzzrF3lFh3GK8Gi4ZdtC3h206Bq98")
os.environ["LANGCHAIN_API_KEY"] = userdata.get("LANGCHAIN_API_KEY")
os.environ["LANGCHAIN_PROJECT"] = "Web-Based-Tracing-Using-Langsmith"
os.environ["LANGCHAIN_TRACING_V2"] = "true"

"""# ***Create The Gemini Pro LLM For Getting Answer Related to Our Context***"""

llm = genai.GenerativeModel(model_name = "models/gemini-1.5-pro")
def answer_question(question, embed_model, index, chunks):
    question_embedding = embed_model.encode([question])
    D, I = index.search(np.array(question_embedding), k=5)
    retrieved_chunks = [chunks[i] for i in I[0]]

    # Combine into one context
    context = "\n".join(retrieved_chunks)

    # Generate answer using Gemini
    prompt = f"""You are a helpful AI assistant. Answer the following question strictly using the provided content.

     Context:
    {context}

    Question: {question}

    Answer:"""

    response = llm.generate_content(prompt)
    return response.text, context

urls = [
    "https://www.geeksforgeeks.org/machine-learning/",
    "https://www.ibm.com/topics/deep-learning"
]

"""# ***Function For Getting Urls***"""

def get_urls_from_user():
    print("🔗 Enter URLs one by one. Type 'done' when finished.\n")
    urls = []
    while True:
        url = input("Enter URL: ")
        if url.lower() == 'done':
            break
        if url.startswith("http://") or url.startswith("https://"):
            urls.append(url)
        else:
            print("⚠️ Please enter a valid URL (starting with http or https).")
    return urls

urls = get_urls_from_user()

raw_text = extract_text_from_urls(urls)
chunks = split_into_chunks(raw_text, chunk_size=150)
faiss_index, _ = create_faiss_index(chunks)

"""# ***Test Our Model Using Gemin-Pro-1.5-Vision***"""

q = input("Ask The Question Realed to Provided Url")
answer, context = answer_question(q, embed_model, faiss_index, chunks)
print("\n🧠 Answer:", answer.strip())
print("\n📌 Context Preview:\n", context[:400], "\n" + "-"*80)

"""# ***Install Gradio***"""

! pip install gradio

"""# ***Live Running My Project Using Gradio***"""

def generate_answer_from_chunk(question, top_chunk, chunk_list, idx, num_neighbors=5):

    context_start = max(0, idx - num_neighbors)
    context_end = min(len(chunk_list), idx + num_neighbors + 1)
    full_context = " ".join(chunk_list[context_start:context_end])

    # Return the generated answer with a more comprehensive context
    return f"Based on the content, here's what was found: {top_chunk[:800]}..."


def run_qa(url_input, question):
    urls = [u.strip() for u in url_input.split(",") if u.strip().startswith("http")]
    if not urls or not question.strip():
        return "❗ Please enter valid URLs and a question.", ""

    texts = [fetch_text(u) for u in urls]
    chunks = chunk_text(texts)
    index, chunk_list = build_index(chunks)

    # Search relevant chunk
    q_embed = embed_model.encode([question], normalize_embeddings=True)
    _, I = index.search(np.array(q_embed), k=3)
    top_chunk = chunk_list[I[0][0]]

    # Get more context around the selected chunk (using neighboring chunks)
    answer = generate_answer_from_chunk(question, top_chunk, chunk_list, I[0][0])

    # Use the surrounding context as preview
    context = " ".join(chunk_list[max(0, I[0][0] - 2):min(len(chunk_list), I[0][0] + 3)])[:600] + "..."

    return answer, context

# Custom Css File for Black BackGround Purposes
custom_css = """
body {
    background-color: #121212 !important;
    color: #f0f0f0 !important;
}
.gradio-container {
    background-color: #1e1e1e !important;
    color: #f0f0f0 !important;
}
h1 { /* Target the main title element */
    color: #ADD8E6 !important; /* Light blue for good contrast */
}
.gr-textbox > label,
.gr-number > label,
.gr-dropdown > label,
.gr-checkbox-group > label,
.gr-radio > label,
.gr-slider > label,
.gr-image > label,
.gr-file > label,
.gr-dataframe > label,
.gr-json > label,
.gr-highlighted-text > label,
.gr-button > label {
    color: #ccc !important;
}
.gr-textbox input,
.gr-number input,
.gr-dropdown select,
.gr-checkbox-group input[type="checkbox"] + label,
.gr-radio input[type="radio"] + label,
.gr-slider input[type="range"],
.gr-image-upload,
.gr-file-upload,
.gr-dataframe > div > div > input,
.gr-json textarea {
    background-color: #333 !important;
    color: #eee !important;
    border: 1px solid #555 !important;
}
.gr-button {
    background-color: #2196F3 !important;
    color: white !important;
    border: none !important;
    border-radius: 4px !important;
    font-weight: bold !important;
}
.gr-button:hover {
    background-color: #1976D2 !important;
}
.gr-output-textbox,
.gr-output-number,
.gr-output-dataframe > div,
.gr-output-json > pre,
.gr-output-highlighted-text > div {
    background-color: #2a2a2a !important;
    color: #eee !important;
    border: 1px solid #444 !important;
}
"""

gr.Interface(
    fn=run_qa,
    inputs=[
        gr.Textbox(label="🌐 Enter URLs", placeholder="https://example.com, https://another.com"),
        gr.Textbox(label="❓ Your Question", placeholder="e.g. What is AI?")
    ],
    outputs=[
        gr.Textbox(label="🧠 Smart Answer from Page"),
        #gr.Textbox(label="📌 Full Context Preview")

    ],
    title="⚡ Real-Time Web Q&A Bot",
    description="Ask questions from URLs instantly using sentence embeddings and chunked matching.",

    css=custom_css
).launch(share=True)